version: 2.1
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle checkstyleMain
      - run: gradle build -x test -x checkstyleMain
      - run: gradle test
      - store_test_results:
               path: build/test-results
  deploy:
    - docker:
        - image: circleci/openjdk:8-jdk
    -steps:
      - checkout
      - run:
        name: Deploy development to Heroku
        command: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git development

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: development
